[package]
name = "upsa-bo"
version = "0.1.0"
compiler = "0.14.0"
repository = "https://github.com/jassielof/typst-templates"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MIT"
description = "UPSA Bolivia template for graduation projects."
keywords = ["UPSA", "Universidad Privada de Santa Cruz de la Sierra", "Bolivia"]
categories = ["report", "thesis"]
disciplines = []
exclude = ["*.pdf", "reference"]

[template]
path = "template"
entrypoint = "TFG/main.typ"
thumbnail = "thumbnail.png"
