[package]
name = "koma-neu"
version = "0.1.0"
compiler = "0.14.0"
repository = "https://github.com/jassielof/typst-templates"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MPL-2.0"
description = "Port of the KOMA-Script document classes."
keywords = [
  "LaTeX",
  "KOMA-Script",
  "scrartcl",
  "scrreprt",
  "scrbook",
]
categories = ["report", "paper", "book"]
disciplines = []
exclude = ["*.pdf", "reference", "ctan"]

[template]
path = "template"
entrypoint = "scrreprt.typ"
thumbnail = "thumbnail.png"
