[package]
name = "latex-reborn"
version = "0.1.0"
compiler = "0.14.0"
repository = "https://github.com/jassielof/typst-templates"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MPL-2.0"
description = "Port of the LaTeX Standard document classes."
keywords = ["LaTeX", "article", "report", "book", "letter"]
categories = ["report", "paper", "book"]
disciplines = []
exclude = ["*.pdf", "reference"]

[template]
path = "template"
entrypoint = "article.typ"
thumbnail = "thumbnail-article.png"
