[package]
name = "butterick-resume"
version = "0.1.0"
authors = ["Jassiel Ovando <@jassielof>"]
compiler = "0.14.0"
license = "MIT"
entrypoint = "lib.typ"
repository = "https://github.com/jassielof/typst-templates"
description = "Résumé template based on Matthew Butterick's guide."
categories = ["cv"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
