[package]
name = "acm-suite"
version = "0.1.216"
compiler = "0.14.0"
repository = "https://github.com/jassielof/typst-templates"
entrypoint = "lib.typ"
authors = ["Jassiel Ovando <@jassielof>"]
license = "MPL-2.0"
description = "ACM template suite, port of the LaTeX acm-article template."
keywords = [
  "ACM",
  "Association for Computing Machinery",
  "Computer Science",
  "Research",
  "Academic Writing",
]
categories = ["paper", "report", "thesis"]
disciplines = ["computer-science", "engineering"]
exclude = ["*.pdf", "!assets/**/*.pdf", "reference"]

[template]
path = "template"
entrypoint = "manuscript.typ"
thumbnail = "thumbnail.png"
